export { default as AuthPage } from "./AuthPage";
export { default as CreateGamePage } from "./CreateGamePage";
export { default as GamePage } from "./GamePage";
export { default as InstructionsPage } from "./InstructionsPage";
export { default as JoinGamePage } from "./JoinGamePage";
export { default as MyGamesPage } from "./MyGamesPage";
export { default as OptionsPage } from "./OptionsPage";
export { default as SplashPage } from "./SplashPage";
export { default as StartPage } from "./StartPage";
